= FIESER
KOENIGSEB
v1.0 (1), 2021-05-15: FIESER
:doctype: book
:experimental:
:icons: font
:icon-set: fas
:imagesdir: ./images
:prewrap!:
:sectanchors:
:sectlinks:
:sectnumlevels: 5
:sectnums:
:source-highlighter: coderay
:toc-title: Table des Matières
:toc: left
:toclevels: 2

Version: {revnumber}

Version Date: {revdate}

Version Notes: {revremark}

== COMPOSITION D'ÉQUIPE

- 1 healer dans la salle de contrôle, personne d'autre ne doit rentrer dans la salle, cette dernière étant rapidement verrouillée. (*HEALER*)
- 1 dps qui contrôle l'étage et les escaliers A et C. (*DPSUP*)
- 2 dps proches des écrans allée C. (*DPSC*)
- 1 dps dans l'angle entre les allées A et B. (*DPSAB*) 
- 1 dps qui navigue pour aider entre A et C, uniquement au rez-de-chaussée. (*DPSDOWN*)
- 1 dps proche du sas allée A. (*DPSA*)
- 1 tank allée A qui entrera souvent dans la salle du boss. (*TANK*)


== BUILDS
- Les dps doivent avoir un bon build AR ou PM/calibre 12.
- HEALER doit utiliser des compétences de soin en continu sur lui-même (drone réparateur et ruche reconstituante).
- TANK doit posséder au minimum 1,7M de protection et 80-90% de résistance aux brûlures ; 95-100% fortement recommandé. Il doit aussi posséder 2 à 3% de régénération de protection. Il est préférable d'utiliser La Vorace sur le boss dès que possible pour stacker de la protection bonus en plus de lui infliger un maximum de dégâts dès que possible tout au long des diverses phases.
- À l'exception de HEALER, les 7 autres personnes doivent posséder une ruche de réanimation.

== RÔLES
Chaque joueur à un travail bien précis à mener. Si quelqu'un n'exécute pas à la *perfection* son job, il mettra en péril *toute* l'équipe.

=== DPSC
Ils doivent constamment démober toute l'allée C. L'un des deux devra aider pour une phase ultérieure en brisant des points faibles dans la salle du boss. Si une roquette tombe d'un mob, il faudra ramasser cette dernière et la "briser" en la tirant dans le vide ou sur un mob ; ceci, à chaque roquette, pour qu'elles ne tombent que du côté A.
Ils devront également activer les manivelles d'eau au moment voulu.

=== DPSA
Il devra constamment démober toute l'allée A et le moment venu, activer une ou plusieurs manivelles d'eau. Il devra également prendre les roquettes et les déposer dans le sas où se trouve le tank. Si la porte est fermée car le tank est dans la salle du boss, il peut les déposer juste devant, ce qui permettra au tank de les rentrer lui-même dans le sas.

=== DPSDOWN
1* dps en mouvement entre A et C, en passant par B (uniquement au rez-de-chaussée) : il aidera au démobage dans toutes les allées sans pour autant s'aventurer dans ces dernières (A et C). Il se chargera en partie de regarder les deux écrans pour la phase des codes d'erreur, se trouvant devant le sas B (au spawn), et si besoin de tirer dans les deux boîtiers électroniques liés.

=== DPSUP
1* dps à l'étage : il doit démober tous les mobs à l'étage et dans les escaliers. Il est conseillé que ce soit celui avec le plus gros dps ainsi qu'un Scorpio à disposition pour gérer les mobs tentant de couper l'électricité et les boomer.

=== HEALER
1* healer dans la salle de contrôle : il devra gérer seul la salle de contrôle (ouverture et fermeture des portes, écrans pour les codes d'erreur, niveau d'eau, levier pour envoyer l'eau dans le canon à eau, levier de déplacement du creuset, levier pour verser le creuset sur la lave, rétablissement de l'électricité, etc.).

=== TANK
1* tank sur A : ce dernier doit entrer légèrement dans la salle du boss pour donner au healer les codes d'erreur qui sont affichés sous la porte B, vérifier qu'il possède bien 2 roquettes dans son sas et si ce n'est pas le cas : prévenir les dps de l'allée C pour qu'ils en brisent une dès que possible. Il doit aussi tirer au bon moment et rapidement les deux roquettes sur le canon au fond de la salle du boss, tirer régulièrement sur le boss pour lui entamer sa vie, parfois rester un moment dans la salle du boss pour l'empêcher d'attaquer la salle de contrôle et lui ôter un maximum de protection, rester dans la salle pour attirer le boss pendant qu'un dps de C brise les points faibles du creuset, etc.

== PHASE 1

- TANK entre par la porte A dans la salle du boss, donne à HEALER le code d'erreur et ressort immédiatement dans l'allée A.
- HEALER donne la description du symbole à tout le monde (le creuset plein est celui avec de la couleur blanche dedans).
- DPSA va voir l'écran dans l'angle des allées A et B et TANK va voir l'écran au fond de l'allée A. Les autres dps font de même avec leurs écrans respectifs (1 joueur sur chaque ecran de l'allée C et 1 joueur pour les deux écrans de B).
- Quand quelqu'un voit le symbole sur son écran, il dit "Machin, c'est pour toi" ; puis Machin tire sur son boîtier électrique. Si les écrans deviennent vert, l'étape est réussie.
- Le boss spawn et commence à attaquer la salle de contrôle. TANK doit donc régulièrement l'attirer entre deux phases de codes d'erreur. Si cela n'est pas fait, le boss brisera la vitre de la salle de contrôle et le healer mourera rapidement.
- L'étape des codes d'erreur est à répéter 4 fois après le spawn du boss, soit 5 fois au total (à vérifier, peut-être qu'il faut le faire 4 fois au total).

Durant toute cette phase :

- Si une alarme retentit, TANK doit rapidement tirer les 2 roquettes sur le canon au fond de la salle du boss. Ceci 2 à 3 fois durant toute la phase.
- Si le boss pousse un cri et court vers le canon au fond de la salle, il va effectuer son "doom" qui one shot tout le monde dans la salle. TANK doit donc être dans le sas ou dans l'allée A à ce moment.
- Attention, au moment de refroidir le canon (phase ultérieure), le timing doit être bon pour ne pas que le boss fasse son doom alors que le tank est au canon à eau ; ce sera très difficile d'aller le reanimer même si cela n'est pas réellement nécessaire pour la suite, à la seule condition que l'eau ait bel et bien été projetée sur la lave.(modifié)

== PHASE 2

Une fois la phase des codes d'erreur terminée, des points faibles vont apparaître au plafond, au niveau des côtés de la structure qui soutient le creuset de lave, se trouvant lui-même au centre de la salle.

- TANK doit entrer dans la salle et tirer sur le boss pour le distraire.
- Un DPSC (DPSC+) entre dans son sas.
- HEALER ouvre la porte C.
- DPSC+ tire sur le premier point faible et le brise, sans sortir du sas (il peut entrer légèrement dans la salle du boss pour mieux voir le point faible si besoin).
- HEALER active la poignée pour faire avancer le creuset vers le fond de la salle.
- DPSC+ brise le second point faible.
- HEALER avance le creuset.
- DPSC+ brise le troisième point faible.
- HEALER avance le creuset au-dessus du canon.
- HEALER ouvre à la suite les porte C puis A pour que DPSC+ et TANK puissent chacun leur tour retourner dans leur allée respective.
- HEALER active la poignée pour verser la lave du creuset sur le canon au fond de la salle.

== PHASE 3

La lave étant versée sur le canon pour le mettre hors service, il est maintenant temps d'utiliser un canon à eau pour arroser celle-ci.

- HEALER demande à tout le monde de se mettre devant les manivelles au préalable sélectionnées (valeur de 15 ou 25) ; le total d'eau envoyé devant idéalement être de 85 (25 + 15 + 15 + 15 +15) mais peu aussi être de 90 (25 + 25 + 25 + 15). Préférez 90 si les joueurs ne sont pas assez rapides pour activer les 5 manivelles. DPSDOWN peut venir activer une manivelle sur A. Ainsi, 4 joueurs activent les manivelles, sachant qu'on peut en activer une, puis une autre avec un même joueur (cas de 5 manivelles pour 4 joueurs).
- Les manivelles doivent idéalement être activées en même temps.
- HEALER regarde monter le niveau et communique à l'équipe ce dernier, en précisant les valeurs manquantes (ex : "niveau à 70, manque 15").
- Une fois le niveau requis atteint, HEALER ouvre la porte A à TANK qui doit courir sans s'arrêter, malgré les attaques du boss, vers le canon à eau au fond à gauche sur un piédestal.
- HEALER, juste après avoir laissé entrer le tank, active le levier pour envoyer l'eau aux 2 canons à eau (nous n'en utilisons qu'un).
- TANK arrose avec ce dernier la lave précédemment versée sur le canon central, le jet se coupant tout seul une fois la réserve d'eau épuisée.
- TANK ressort rapidement en direction de l'allée A (souvent, il meurt avant de l'avoir atteint, mais ce n'est pas dramatique).

== PHASE 4

Une fois la lave refroidie grâce au canon à eau, que TANK soit ressorti vivant ou non de la salle :

- HEALER demande à toute la team de se rendre dans le sas B. 7 joueurs devront donc s'y retrouver dans les 20 secondes environ suivant le call.
Attention aux mobs ! démober un minimum est toujours préférable si le temps le permet.
- Une fois tout le monde prêt au combat, le healer ouvre la porte B et les 7 joueurs doivent tomber le boss le plus rapidement possible.
- Une fois le boss tombé, ne pas foncer ramasser les loots, des mobs sont toujours présents dans les 3 allées et possiblement à l'étage. Ils doivent être éliminés.

Il est désormais possible d'accéder en toute sécurité à la salle du boss pour y récupérer son butin.

La sortie vers le prochain boss "Williams" se trouve en face du sas allée A.

== Table des codes

KOENIGSEB a communiqué le tableau suivant :

[cols="3*^m"]
|===
| F#0 | P#5 | C#4
| R#0 | M#2 | #45
|===

HEALER donnera les symboles de la case correspondant au code donné par TANK.